#ifndef __GAME_DEFINE_H__
#define __GAME_DEFINE_H__

enum
{
  ALADDIN_TAG,
  ENEMY_TAG,
  GROUND_TAG,
  WALL_TAG,
  BACKGROUND_TAG,
  FOREGROUND_TAG,
  SWORD_TAG,
  CHARCOAL_BURNER_TAG,
  KNIFE_TAG,
  VASE_TAG,
  ROPE_TAG,
  BAR_TAG,
  SPRING_TAG,
  HUB_TAG,
  APPLE_TAG,
  HORIZONTALBAR_TAG,
  PLATFORM_TAG,
  HEART_TAG,
  LAMP_TAG,
  BONUS_TAG,
  SPEND_TAG,
  ABU_BONUS_TAG,
  ANIMAL_TAG,
  CAMEL_TAG,
  SAVILA_TAG,
  BOSS_TAG,
  FIRE_TAG,
  STAR_TAG,
  FINISH_ENTRANCE_TAG
};

enum
{
  COLLIDE_ALADDIN_FLAG = 1 << 0,
  COLLIDE_ENEMY_FLAG = 1 << 1,
  COLLIDE_FREE_OBJECT_FLAG = 1 << 2,
  STATIC_FLAG = 1 << 3,
  STANDABLE_FLAG = 1 << 4,
  BELONGS_TO_ALADDIN = 1 << 5,
  EMPTY_FLAG = 1 << 31
};

#endif //!__GAME_DEFINE_H__
